---
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/testdb
    username: testproject
    password: testproject
  jpa:
    hibernate.ddl-auto: none
    show_sql: false
